/**
 * Renders one or more schema.org JSON-LD blocks.
 * The payload is always generated by `@/lib/seo`, never user input, so
 * `dangerouslySetInnerHTML` is safe here — it's the only way to emit a
 * `<script type="application/ld+json">` body in React.
 */
export function JsonLd({ data }: { data: object | object[] }) {
  const payload = Array.isArray(data) ? data : [data];

  return (
    <>
      {payload.map((item, index) => (
        <script
          key={index}
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(item) }}
        />
      ))}
    </>
  );
}
